default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 8 } %>
  encoding: utf8
  username: review_scraper
  password: shSuGjT5UO4VBIUNpfLBdeiJ

development:
  <<: *default
  database: review-scraper-development
  host: localhost

test:
  <<: *default
  database: review-scraper-test
  host: localhost
